In [4]:
import pandas as pd
import numpy as np
from rdkit import Chem
import matplotlib.pyplot as plt
import seaborn as sns
from rdkit.Chem import Descriptors

In [5]:
df=pd.read_excel("../data/Solubility_data_with_families.xlsx")

In [6]:
df.head()

,IL NAME,CATION NAME,ANION NAME,Cation_SMILES,Anion_SMILES,Temperature (0 C),Pressure (bar),CO2 capacity (mol CO2/mol IL),Cation_Family
0,[Bmim][PF6],1-butyl-3-methyl-imidazolium,hexafluorophosphate,CCCC[n+]1ccn(C)c1,F[P-](F)(F)(F)(F)F,25.0,83.0,0.75,Imidazolium
1,[Emim][Tf2N],1-ethyl-3-methylimidazolium,bis(trifluoromethylsulfonyl)imide,CC[n+]1ccn(C)c1,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,100.0,13.0,0.17,Imidazolium
2,[Bmim][Tf2N],1-butyl-3-methyl-imidazolium,bis(trifluoromethylsulfonyl)imide,CCCC[n+]1ccn(C)c1,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,100.0,13.0,0.18,Imidazolium
3,[Omim][Tf2N],1-octyl-3-methyl-imidazolium,bis(trifluoromethylsulfonyl)imide,CCCCCCCC[n+]1ccn(C)c1,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,100.0,13.0,0.19,Imidazolium
4,[C12mim][Tf2N],1-dodecyl-3-methyl-imidazolium,bis(trifluoromethylsulfonyl)imide,CCCCCCCCCCCC[n+]1ccn(C)c1,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,100.0,13.0,0.21,Imidazolium

In [7]:
m=Chem.MolFromSmiles(df.loc[6,"Cation_SMILES"])
Descriptors.TPSA(m)

8.809999999999999

In [8]:
vals = Descriptors.CalcMolDescriptors(m)
vals['TPSA']

8.809999999999999

In [9]:
mols=[]
for m in df["Cation_SMILES"]:
    mols.append(Chem.MolFromSmiles(m))

In [10]:
descrs = [Descriptors.CalcMolDescriptors(mol) for mol in mols]
desc = pd.DataFrame(descrs)

In [11]:
desc.sample(7)

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
4640,2.245694,2.245694,1.167500,1.167500,0.467595,10.500000,167.276,148.124,167.154275,68,...,0,0,0,0,0,0,0,0,3,0
1308,2.245694,2.245694,1.167500,1.167500,0.467595,10.500000,167.276,148.124,167.154275,68,...,0,0,0,0,0,0,0,0,3,0
4473,3.486111,3.486111,1.000000,1.000000,0.371491,6.000000,46.093,38.029,46.065126,20,...,0,0,0,0,0,0,0,0,0,0
3497,3.674173,3.674173,1.108472,1.108472,0.578815,9.909091,151.233,136.113,151.122975,60,...,0,0,0,0,0,0,0,0,1,0
4030,2.245694,2.245694,1.167500,1.167500,0.467595,10.500000,167.276,148.124,167.154275,68,...,0,0,0,0,0,0,0,0,3,0
5304,2.225139,2.225139,1.315972,1.315972,0.508614,10.285714,102.201,86.073,102.127726,44,...,0,0,0,0,0,0,0,0,1,0
7,2.211806,2.211806,1.150139,1.150139,0.554691,10.200000,139.222,124.102,139.122975,56,...,0,0,0,0,0,0,0,0,1,0

In [18]:
desc.isnull().sum().sum()

np.int64(0)

In [19]:
desc.columns = ["Cat_" + col for col in desc.columns]

In [20]:
desc.head()

,Cat_MaxAbsEStateIndex,Cat_MaxEStateIndex,Cat_MinAbsEStateIndex,Cat_MinEStateIndex,Cat_qed,Cat_SPS,Cat_MolWt,Cat_HeavyAtomMolWt,Cat_ExactMolWt,Cat_NumValenceElectrons,...,Cat_fr_sulfide,Cat_fr_sulfonamd,Cat_fr_sulfone,Cat_fr_term_acetylene,Cat_fr_tetrazole,Cat_fr_thiazole,Cat_fr_thiocyan,Cat_fr_thiophene,Cat_fr_unbrch_alkane,Cat_fr_urea
0,2.211806,2.211806,1.150139,1.150139,0.554691,10.200000,139.222,124.102,139.122975,56,...,0,0,0,0,0,0,0,0,1,0
1,2.125000,2.125000,1.056389,1.056389,0.461795,9.750000,111.168,100.080,111.091675,44,...,0,0,0,0,0,0,0,0,0,0
2,2.211806,2.211806,1.150139,1.150139,0.554691,10.200000,139.222,124.102,139.122975,56,...,0,0,0,0,0,0,0,0,1,0
3,2.263711,2.263711,1.173576,1.173576,0.467050,10.714286,195.330,172.146,195.185575,80,...,0,0,0,0,0,0,0,0,5,0
4,2.282488,2.282488,1.177917,1.177917,0.410874,11.000000,251.438,220.190,251.248175,104,...,0,0,0,0,0,0,0,0,9,0

In [30]:
desc.describe()

,Cat_MaxAbsEStateIndex,Cat_MaxEStateIndex,Cat_MinAbsEStateIndex,Cat_MinEStateIndex,Cat_qed,Cat_SPS,Cat_MolWt,Cat_HeavyAtomMolWt,Cat_ExactMolWt,Cat_NumValenceElectrons,...,Cat_fr_sulfide,Cat_fr_sulfonamd,Cat_fr_sulfone,Cat_fr_term_acetylene,Cat_fr_tetrazole,Cat_fr_thiazole,Cat_fr_thiocyan,Cat_fr_thiophene,Cat_fr_unbrch_alkane,Cat_fr_urea
count,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,...,5349.0,5349.0,5349.0,5349.0,5349.0,5349.0,5349.0,5349.0,5349.000000,5349.0
mean,3.113498,3.113498,1.028575,0.863775,0.500547,11.559203,155.490619,137.914974,155.380946,62.824079,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.570761,0.0
std,2.119076,2.119076,0.295891,1.074778,0.078408,3.697888,51.294376,46.630665,51.264910,20.542418,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.307692,0.0
min,2.125000,2.125000,0.122336,-7.856082,0.076609,6.000000,46.093000,38.029000,46.065126,20.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
25%,2.211806,2.211806,1.056389,1.056389,0.467050,10.200000,130.255000,116.079000,130.159026,54.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
50%,2.255899,2.255899,1.150139,1.150139,0.495865,10.285714,141.194000,124.102000,141.102239,56.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0
75%,2.414768,2.414768,1.167500,1.167500,0.554691,10.714286,167.276000,148.124000,167.154275,68.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.000000,0.0
max,13.495084,13.495084,1.366806,1.366806,0.758479,30.454545,483.870000,419.120000,483.505315,200.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.000000,0.0

In [32]:
mols_anion=[]
for m in df["Anion_SMILES"]:
    mols_anion.append(Chem.MolFromSmiles(m))

In [33]:
descrs_an = [Descriptors.CalcMolDescriptors(mol) for mol in mols_anion]
desc_an = pd.DataFrame(descrs_an)

In [39]:
desc_an.describe()

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
count,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,...,5349.000000,5349.000000,5349.0,5349.0,5349.0,5349.0,5349.000000,5349.0,5349.000000,5349.0
mean,10.274110,10.137822,2.295218,-5.349937,0.503539,13.551494,191.147667,189.716982,191.039543,65.250888,...,0.000187,0.772107,0.0,0.0,0.0,0.0,0.004300,0.0,0.010282,0.0
std,2.089564,1.937385,3.182509,3.649965,0.174699,5.526100,112.889864,113.708215,112.815334,37.421789,...,0.013673,0.973777,0.0,0.0,0.0,0.0,0.065438,0.0,0.113121,0.0
min,0.000000,0.000000,0.000000,-17.482569,0.162915,0.000000,15.035000,12.011000,15.024024,8.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
25%,9.462963,9.462963,0.421528,-6.721528,0.361605,11.714286,90.065000,90.065000,90.009771,32.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
50%,10.657407,10.027963,0.777778,-6.721528,0.445972,15.333333,145.182000,144.962000,145.098251,56.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
75%,11.438426,11.438426,1.750000,-1.359954,0.707973,15.333333,280.147000,280.147000,279.917842,92.000000,...,0.000000,2.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
max,17.482569,14.753866,9.865741,1.638889,0.707973,28.250000,745.046000,745.046000,744.926407,264.000000,...,1.000000,2.000000,0.0,0.0,0.0,0.0,1.000000,0.0,4.000000,0.0

In [38]:
desc_an.isnull().sum().sum()

np.int64(7992)

In [40]:
invalid_anions = 0

for smile in df["Anion_SMILES"]:

    mol = Chem.MolFromSmiles(smile)

    if mol is None:
        invalid_anions += 1

print(invalid_anions)

0

In [46]:
desc_an.columns = [
    col.replace("AN_Cat_", "An_")
    for col in desc_an.columns
]

In [48]:
desc.head()

,Cat_MaxAbsEStateIndex,Cat_MaxEStateIndex,Cat_MinAbsEStateIndex,Cat_MinEStateIndex,Cat_qed,Cat_SPS,Cat_MolWt,Cat_HeavyAtomMolWt,Cat_ExactMolWt,Cat_NumValenceElectrons,...,Cat_fr_sulfide,Cat_fr_sulfonamd,Cat_fr_sulfone,Cat_fr_term_acetylene,Cat_fr_tetrazole,Cat_fr_thiazole,Cat_fr_thiocyan,Cat_fr_thiophene,Cat_fr_unbrch_alkane,Cat_fr_urea
0,2.211806,2.211806,1.150139,1.150139,0.554691,10.200000,139.222,124.102,139.122975,56,...,0,0,0,0,0,0,0,0,1,0
1,2.125000,2.125000,1.056389,1.056389,0.461795,9.750000,111.168,100.080,111.091675,44,...,0,0,0,0,0,0,0,0,0,0
2,2.211806,2.211806,1.150139,1.150139,0.554691,10.200000,139.222,124.102,139.122975,56,...,0,0,0,0,0,0,0,0,1,0
3,2.263711,2.263711,1.173576,1.173576,0.467050,10.714286,195.330,172.146,195.185575,80,...,0,0,0,0,0,0,0,0,5,0
4,2.282488,2.282488,1.177917,1.177917,0.410874,11.000000,251.438,220.190,251.248175,104,...,0,0,0,0,0,0,0,0,9,0

In [49]:
desc.describe()

,Cat_MaxAbsEStateIndex,Cat_MaxEStateIndex,Cat_MinAbsEStateIndex,Cat_MinEStateIndex,Cat_qed,Cat_SPS,Cat_MolWt,Cat_HeavyAtomMolWt,Cat_ExactMolWt,Cat_NumValenceElectrons,...,Cat_fr_sulfide,Cat_fr_sulfonamd,Cat_fr_sulfone,Cat_fr_term_acetylene,Cat_fr_tetrazole,Cat_fr_thiazole,Cat_fr_thiocyan,Cat_fr_thiophene,Cat_fr_unbrch_alkane,Cat_fr_urea
count,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,...,5349.0,5349.0,5349.0,5349.0,5349.0,5349.0,5349.0,5349.0,5349.000000,5349.0
mean,3.113498,3.113498,1.028575,0.863775,0.500547,11.559203,155.490619,137.914974,155.380946,62.824079,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.570761,0.0
std,2.119076,2.119076,0.295891,1.074778,0.078408,3.697888,51.294376,46.630665,51.264910,20.542418,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.307692,0.0
min,2.125000,2.125000,0.122336,-7.856082,0.076609,6.000000,46.093000,38.029000,46.065126,20.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
25%,2.211806,2.211806,1.056389,1.056389,0.467050,10.200000,130.255000,116.079000,130.159026,54.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
50%,2.255899,2.255899,1.150139,1.150139,0.495865,10.285714,141.194000,124.102000,141.102239,56.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0
75%,2.414768,2.414768,1.167500,1.167500,0.554691,10.714286,167.276000,148.124000,167.154275,68.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.000000,0.0
max,13.495084,13.495084,1.366806,1.366806,0.758479,30.454545,483.870000,419.120000,483.505315,200.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.000000,0.0

In [47]:
desc_an.head()

,An_MaxAbsEStateIndex,An_MaxEStateIndex,An_MinAbsEStateIndex,An_MinEStateIndex,An_qed,An_SPS,An_MolWt,An_HeavyAtomMolWt,An_ExactMolWt,An_NumValenceElectrons,...,An_fr_sulfide,An_fr_sulfonamd,An_fr_sulfone,An_fr_term_acetylene,An_fr_tetrazole,An_fr_thiazole,An_fr_thiocyan,An_fr_thiophene,An_fr_unbrch_alkane,An_fr_urea
0,10.657407,9.865741,9.865741,-10.657407,0.361605,23.142857,144.962,144.962,144.964730,48,...,0,0,0,0,0,0,0,0,0,0
1,11.438426,11.438426,0.777778,-6.721528,0.707973,15.333333,280.147,280.147,279.917842,92,...,0,2,0,0,0,0,0,0,0,0
2,11.438426,11.438426,0.777778,-6.721528,0.707973,15.333333,280.147,280.147,279.917842,92,...,0,2,0,0,0,0,0,0,0,0
3,11.438426,11.438426,0.777778,-6.721528,0.707973,15.333333,280.147,280.147,279.917842,92,...,0,2,0,0,0,0,0,0,0,0
4,11.438426,11.438426,0.777778,-6.721528,0.707973,15.333333,280.147,280.147,279.917842,92,...,0,2,0,0,0,0,0,0,0,0

In [50]:
desc_an.describe()

,An_MaxAbsEStateIndex,An_MaxEStateIndex,An_MinAbsEStateIndex,An_MinEStateIndex,An_qed,An_SPS,An_MolWt,An_HeavyAtomMolWt,An_ExactMolWt,An_NumValenceElectrons,...,An_fr_sulfide,An_fr_sulfonamd,An_fr_sulfone,An_fr_term_acetylene,An_fr_tetrazole,An_fr_thiazole,An_fr_thiocyan,An_fr_thiophene,An_fr_unbrch_alkane,An_fr_urea
count,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,...,5349.000000,5349.000000,5349.0,5349.0,5349.0,5349.0,5349.000000,5349.0,5349.000000,5349.0
mean,10.274110,10.137822,2.295218,-5.349937,0.503539,13.551494,191.147667,189.716982,191.039543,65.250888,...,0.000187,0.772107,0.0,0.0,0.0,0.0,0.004300,0.0,0.010282,0.0
std,2.089564,1.937385,3.182509,3.649965,0.174699,5.526100,112.889864,113.708215,112.815334,37.421789,...,0.013673,0.973777,0.0,0.0,0.0,0.0,0.065438,0.0,0.113121,0.0
min,0.000000,0.000000,0.000000,-17.482569,0.162915,0.000000,15.035000,12.011000,15.024024,8.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
25%,9.462963,9.462963,0.421528,-6.721528,0.361605,11.714286,90.065000,90.065000,90.009771,32.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
50%,10.657407,10.027963,0.777778,-6.721528,0.445972,15.333333,145.182000,144.962000,145.098251,56.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
75%,11.438426,11.438426,1.750000,-1.359954,0.707973,15.333333,280.147000,280.147000,279.917842,92.000000,...,0.000000,2.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
max,17.482569,14.753866,9.865741,1.638889,0.707973,28.250000,745.046000,745.046000,744.926407,264.000000,...,1.000000,2.000000,0.0,0.0,0.0,0.0,1.000000,0.0,4.000000,0.0

In [54]:
df_fin=pd.concat([df,desc,desc_an],axis=1)

In [55]:
df_fin.head()

,IL NAME,CATION NAME,ANION NAME,Cation_SMILES,Anion_SMILES,Temperature (0 C),Pressure (bar),CO2 capacity (mol CO2/mol IL),Cation_Family,Cat_MaxAbsEStateIndex,...,An_fr_sulfide,An_fr_sulfonamd,An_fr_sulfone,An_fr_term_acetylene,An_fr_tetrazole,An_fr_thiazole,An_fr_thiocyan,An_fr_thiophene,An_fr_unbrch_alkane,An_fr_urea
0,[Bmim][PF6],1-butyl-3-methyl-imidazolium,hexafluorophosphate,CCCC[n+]1ccn(C)c1,F[P-](F)(F)(F)(F)F,25.0,83.0,0.75,Imidazolium,2.211806,...,0,0,0,0,0,0,0,0,0,0
1,[Emim][Tf2N],1-ethyl-3-methylimidazolium,bis(trifluoromethylsulfonyl)imide,CC[n+]1ccn(C)c1,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,100.0,13.0,0.17,Imidazolium,2.125000,...,0,2,0,0,0,0,0,0,0,0
2,[Bmim][Tf2N],1-butyl-3-methyl-imidazolium,bis(trifluoromethylsulfonyl)imide,CCCC[n+]1ccn(C)c1,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,100.0,13.0,0.18,Imidazolium,2.211806,...,0,2,0,0,0,0,0,0,0,0
3,[Omim][Tf2N],1-octyl-3-methyl-imidazolium,bis(trifluoromethylsulfonyl)imide,CCCCCCCC[n+]1ccn(C)c1,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,100.0,13.0,0.19,Imidazolium,2.263711,...,0,2,0,0,0,0,0,0,0,0
4,[C12mim][Tf2N],1-dodecyl-3-methyl-imidazolium,bis(trifluoromethylsulfonyl)imide,CCCCCCCCCCCC[n+]1ccn(C)c1,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,100.0,13.0,0.21,Imidazolium,2.282488,...,0,2,0,0,0,0,0,0,0,0

In [57]:
df_fin.isnull().sum().sum()

np.int64(7992)

In [58]:
df_fin.describe()

,Temperature (0 C),Pressure (bar),CO2 capacity (mol CO2/mol IL),Cat_MaxAbsEStateIndex,Cat_MaxEStateIndex,Cat_MinAbsEStateIndex,Cat_MinEStateIndex,Cat_qed,Cat_SPS,Cat_MolWt,...,An_fr_sulfide,An_fr_sulfonamd,An_fr_sulfone,An_fr_term_acetylene,An_fr_tetrazole,An_fr_thiazole,An_fr_thiocyan,An_fr_thiophene,An_fr_unbrch_alkane,An_fr_urea
count,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,...,5349.000000,5349.000000,5349.0,5349.0,5349.0,5349.0,5349.000000,5349.0,5349.000000,5349.0
mean,43.361554,16.809779,0.351997,3.113498,3.113498,1.028575,0.863775,0.500547,11.559203,155.490619,...,0.000187,0.772107,0.0,0.0,0.0,0.0,0.004300,0.0,0.010282,0.0
std,21.041986,28.551239,0.556316,2.119076,2.119076,0.295891,1.074778,0.078408,3.697888,51.294376,...,0.013673,0.973777,0.0,0.0,0.0,0.0,0.065438,0.0,0.113121,0.0
min,4.970000,0.000013,0.000000,2.125000,2.125000,0.122336,-7.856082,0.076609,6.000000,46.093000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
25%,25.000000,2.000000,0.070664,2.211806,2.211806,1.056389,1.056389,0.467050,10.200000,130.255000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
50%,40.000000,8.442000,0.186000,2.255899,2.255899,1.150139,1.150139,0.495865,10.285714,141.194000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
75%,59.980000,17.100000,0.412429,2.414768,2.414768,1.167500,1.167500,0.554691,10.714286,167.276000,...,0.000000,2.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
max,139.950000,345.500000,8.293680,13.495084,13.495084,1.366806,1.366806,0.758479,30.454545,483.870000,...,1.000000,2.000000,0.0,0.0,0.0,0.0,1.000000,0.0,4.000000,0.0

In [60]:
df_fin.to_csv("../data/DataWithDescriptors.csv")